version: '3'

services:
 backend: 
  build: ./recommend-me-backend
  volumes:
   - h2-volume:/usr/app
  ports:
   - 8080:8080
 frontend:
  build: ./recommend-me-frontend
  volumes:
   - ./recommend-me-frontend:/app
   - f-volume:/app/node_modules
  ports:
   - 3001:3000
volumes:
 h2-volume:
 f-volume:
